### ISSUE TITLE
Problem with node

### ISSUE THREAD

**Issue by pkozakCC** [LoyaltyOne/docker-mirror#3]
Hi.
When I try to run docker-mirror using command
`docker run -d --name docker-mirror -p 9001:9000 --restart always -v /var/run/docker.sock:/var/run/docker.sock -v /etc/hostip:/etc/hostip loyaltyone/docker-mirror:0.1.2`
I get following error:
```
2018-01-02T16:23:41.978481640Z npm info it worked if it ends with ok
2018-01-02T16:23:41.978704655Z npm info using npm@4.2.0
2018-01-02T16:23:41.978714641Z npm info using node@v7.10.1
2018-01-02T16:23:42.139526853Z npm info lifecycle docker-mirror@0.1.2~prestart: docker-mirror@0.1.2
2018-01-02T16:23:42.146441902Z npm info lifecycle docker-mirror@0.1.2~start: docker-mirror@0.1.2
2018-01-02T16:23:42.149672011Z 
2018-01-02T16:23:42.149702920Z > docker-mirror@0.1.2 start /opt/app
2018-01-02T16:23:42.149705890Z > ./start.sh main.js
2018-01-02T16:23:42.149707982Z 
2018-01-02T16:23:42.402800108Z 
2018-01-02T16:23:42.402818818Z /opt/app/node_modules/assert-plus/assert.js:22
2018-01-02T16:23:42.402821655Z     throw new assert.AssertionError({
2018-01-02T16:23:42.402823630Z     ^
2018-01-02T16:23:42.402825614Z AssertionError: hostIp (string) is required
2018-01-02T16:23:42.402827453Z     at Object.create (/opt/app/lib/server.js:73:10)
2018-01-02T16:23:42.402829280Z     at main (/opt/app/main.js:36:33)
2018-01-02T16:23:42.402831066Z     at Object.<anonymous> (/opt/app/main.js:50:3)
2018-01-02T16:23:42.402833197Z     at Module._compile (module.js:571:32)
2018-01-02T16:23:42.402834995Z     at Object.Module._extensions..js (module.js:580:10)
2018-01-02T16:23:42.402836832Z     at Module.load (module.js:488:32)
2018-01-02T16:23:42.402838625Z     at tryModuleLoad (module.js:447:12)
2018-01-02T16:23:42.402840432Z     at Function.Module._load (module.js:439:3)
2018-01-02T16:23:42.402842214Z     at Module.runMain (module.js:605:10)
2018-01-02T16:23:42.402844007Z     at run (bootstrap_node.js:427:7)
2018-01-02T16:23:42.405941259Z 
2018-01-02T16:23:42.407052550Z npm info lifecycle docker-mirror@0.1.2~start: Failed to exec start script
2018-01-02T16:23:42.407068121Z npm ERR! Linux 4.4.0-103-generic
2018-01-02T16:23:42.407139447Z npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--"
2018-01-02T16:23:42.407153625Z npm ERR! node v7.10.1
2018-01-02T16:23:42.407229101Z npm ERR! npm  v4.2.0
2018-01-02T16:23:42.407233513Z npm ERR! code ELIFECYCLE
2018-01-02T16:23:42.407305040Z npm ERR! errno 1
2018-01-02T16:23:42.407309062Z npm ERR! docker-mirror@0.1.2 start: `./start.sh main.js`
2018-01-02T16:23:42.407311713Z npm ERR! Exit status 1
2018-01-02T16:23:42.407382407Z npm ERR! 
2018-01-02T16:23:42.407386139Z npm ERR! Failed at the docker-mirror@0.1.2 start script './start.sh main.js'.
2018-01-02T16:23:42.407453865Z npm ERR! Make sure you have the latest version of node.js and npm installed.
2018-01-02T16:23:42.407575963Z npm ERR! If you do, this is most likely a problem with the docker-mirror package,
2018-01-02T16:23:42.407579857Z npm ERR! not with npm itself.
2018-01-02T16:23:42.407589399Z npm ERR! Tell the author that this fails on your system:
2018-01-02T16:23:42.407654002Z npm ERR!     ./start.sh main.js
2018-01-02T16:23:42.407657837Z npm ERR! You can get information on how to open an issue for this project with:
2018-01-02T16:23:42.407660948Z npm ERR!     npm bugs docker-mirror
2018-01-02T16:23:42.409218227Z npm ERR! Or if that isn't available, you can get their info via:
2018-01-02T16:23:42.409671768Z npm ERR!     npm owner ls docker-mirror
2018-01-02T16:23:42.409683496Z npm ERR! There is likely additional logging output above.
2018-01-02T16:23:42.422588893Z 
2018-01-02T16:23:42.422689673Z npm ERR! Please include the following file with any support request:
2018-01-02T16:23:42.422700782Z npm ERR!     /root/.npm/_logs/2018-01-02T16_23_42_411Z-debug.log
```

**Comment by calvinlfer** [comment]
Hello there, 
This happens when you don't provide a hostip file containing the IP of the host machine located at `/etc/hostip` and try to mount `/etc/hostip` into the container. Once you have a valid hostip file, Docker Mirror will start up. 

```bash
C:\Users\windows-pc>docker run --name docker-mirror -p 9001:9000 -v e:/hostip.txt:/etc/hostip loyaltyone/docker-mirror:0.1.2
npm info it worked if it ends with ok
npm info using npm@4.2.0
npm info using node@v7.10.1
npm info lifecycle docker-mirror@0.1.2~prestart: docker-mirror@0.1.2
npm info lifecycle docker-mirror@0.1.2~start: docker-mirror@0.1.2

> docker-mirror@0.1.2 start /opt/app
> ./start.sh main.js

{"name":"docker-mirror","hostname":"202fcf74ed3f","pid":19,"level":30,"msg":"Registering GET at uri /container/:id/port/:port","time":"2018-01-03T05:53:40.598Z","v":0}
{"name":"docker-mirror","hostname":"202fcf74ed3f","pid":19,"level":30,"msg":"Registering GET at uri /hostip","time":"2018-01-03T05:53:40.600Z","v":0}
{"name":"docker-mirror","hostname":"202fcf74ed3f","pid":19,"level":30,"msg":"Registering GET at uri /health","time":"2018-01-03T05:53:40.601Z","v":0}
{"name":"docker-mirror","hostname":"202fcf74ed3f","pid":19,"level":30,"msg":"listening at http://[::]:9000","time":"2018-01-03T05:53:40.605Z","v":0}
```
